### ISSUE TITLE
ClientRequestException for .load_by_fileName()

### ISSUE THREAD

**Issue by YuliaZamriy** [MODA-NYC/db-recovery-data-partnership#81]
I was following the instructions in README successfully until `df = betanyc.load_by_fileName('betanyc.csv')`, which produced an exception:
`ClientRequestException: ('-2147024891, System.UnauthorizedAccessException', 'Access denied. You do not have permission to perform this action or access this resource.', "403 Client Error: Forbidden for url: https://nyccityhall.sharepoint.com/sites/RDPDataRepository/_api/Web/getFolderByServerRelativeUrl('')")`

My username and password work to login into Sharepoint from a browser.

**Comment by SPTKL** [comment]
Hi @YuliaZamriy, for people with permission as `visitors`, `getFolderByServerRelativeUrl('')` is not allowed. 
So I fixed the issue by rewriting the method that calls `getFolderByServerRelativeUrl('')`, and it should be fixed by now. 
You can do a `pip install rdptools -U`  to update the package. Let me know if the issue persists

**Comment by objornsson** [comment]
Thanks @SPTKL - let me know if we should sync up on permissions for the Sharepoint to ensure this isn't a problem as we do custom permissions for agency analysts going forward
